language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-poole' ]; then cd .. && eval "mv $currentfolder generator-poole" && cd generator-poole; fi
  - bundle install
