# Pull gems from RubyGems
source 'https://rubygems.org'

# Jekyll itself.
gem 'jekyll', '~>2.0'

group :jekyll_plugins do
  # Some base Jekyll plugins that are nice to have.
  gem 'jekyll-sitemap'
  gem 'jekyll-redirect-from'

  # Asset Pipline
  gem 'jekyll-assets'
  gem 'uglifier'
  gem 'yui-compressor'

  # Mr. Poole's Tools
  gem 'jekyll-poole'
end
